# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Excelinp', '0002_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='Price3',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
